import {
  BookOpen,
  Dumbbell,
  FileText,
  Laptop,
  LampDesk,
  Package,
  PenTool,
  Scissors,
  Shirt,
} from "lucide-react";
import type { Category, Conversation, Order, Product, Review, Seller } from "@/types";

export const sellers: Seller[] = [
  {
    id: "daniel-k",
    name: "Daniel K.",
    accountType: "Student",
    handle: "@danieltech",
    avatar: "DK",
    rating: 4.9,
    reviews: 42,
    location: "Hostel C",
    joined: "2024",
    verified: true,
    premium: true,
    responseTime: "Usually replies in 8 min",
    bio: "Final year computer science student selling clean gadgets, textbooks, and study accessories around HTU.",
    banner: "Reliable campus tech deals",
    analytics: { viewsThisWeek: 1240, productClicks: 318, interestedBuyers: 51 },
  },
  {
    id: "amara-b",
    name: "Amara B.",
    accountType: "Local vendor",
    handle: "@amarafinds",
    avatar: "AB",
    rating: 4.8,
    reviews: 31,
    location: "Market Circle",
    joined: "2023",
    verified: true,
    premium: false,
    responseTime: "Usually replies in 20 min",
    bio: "Curated student essentials, outfits, and affordable room items for campus life.",
    banner: "Student essentials with fair prices",
    analytics: { viewsThisWeek: 620, productClicks: 146, interestedBuyers: 24 },
  },
  {
    id: "sarah-t",
    name: "Sarah T.",
    accountType: "Student",
    handle: "@sarahnotes",
    avatar: "ST",
    rating: 4.7,
    reviews: 26,
    location: "Engineering Block",
    joined: "2025",
    verified: false,
    premium: true,
    responseTime: "Usually replies in 12 min",
    bio: "Organized notes, textbooks, stationery, and neat school supplies for HTU students.",
    banner: "Study smarter this semester",
    analytics: { viewsThisWeek: 840, productClicks: 211, interestedBuyers: 37 },
  },
];

export const products: Product[] = [
  {
    id: "campus-tutoring",
    title: "Math and programming tutoring",
    price: 60,
    category: "Services",
    location: "Ho Technical University",
    description: "One-on-one tutoring for calculus, programming basics, and exam revision. Available on campus or around Ho.",
    condition: "New",
    postedAt: "Today",
    sellerId: "sarah-t",
    seller: sellers[2]!,
    featured: true,
    boosted: false,
    negotiable: true,
    tags: ["tutoring", "lectures", "programming"],
    imageStyle: "art-services",
    imageUrl:
      "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=900&q=80",
    views: 144,
  },
  {
    id: "macbook-air-m1",
    title: "MacBook Air M1 256GB",
    price: 4250,
    category: "Electronics",
    location: "HTU Main Gate",
    description: "Clean MacBook Air M1 with strong battery health, charger, and protective sleeve. Perfect for coding, design, and lecture notes.",
    condition: "Like new",
    postedAt: "Today",
    sellerId: "daniel-k",
    seller: sellers[0]!,
    featured: true,
    boosted: true,
    negotiable: true,
    tags: ["laptop", "apple", "coding"],
    imageStyle: "art-laptop",
    imageUrl:
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=900&q=80",
    views: 412,
  },
  {
    id: "calculus-textbook",
    title: "Engineering Calculus Textbook",
    price: 95,
    category: "Textbooks",
    location: "Engineering Block",
    description: "Well-kept calculus textbook with only light pencil notes. Useful for first and second year engineering courses.",
    condition: "Good",
    postedAt: "1 day ago",
    sellerId: "sarah-t",
    seller: sellers[2]!,
    featured: false,
    boosted: false,
    negotiable: true,
    tags: ["math", "engineering", "book"],
    imageStyle: "art-book",
    imageUrl:
      "https://images.unsplash.com/photo-1519682337058-a94d519337bc?auto=format&fit=crop&w=900&q=80",
    views: 103,
  },
  {
    id: "airpods-pro",
    title: "AirPods Pro 2",
    price: 780,
    category: "Electronics",
    location: "SRC Cafeteria",
    description: "Original AirPods Pro 2 with active noise cancellation. Comes with case and spare tips.",
    condition: "Like new",
    postedAt: "2 days ago",
    sellerId: "daniel-k",
    seller: sellers[0]!,
    featured: true,
    boosted: true,
    negotiable: false,
    tags: ["audio", "apple", "wireless"],
    imageStyle: "art-earbuds",
    imageUrl:
      "https://images.unsplash.com/photo-1512499617640-c2f999018b72?auto=format&fit=crop&w=900&q=80",
    views: 289,
  },
  {
    id: "study-desk-chair",
    title: "Study Desk Chair",
    price: 180,
    category: "Furniture",
    location: "Hostel B",
    description: "Comfortable desk chair for hostel rooms. Strong frame, clean fabric, easy pickup.",
    condition: "Good",
    postedAt: "3 days ago",
    sellerId: "amara-b",
    seller: sellers[1]!,
    featured: false,
    boosted: false,
    negotiable: true,
    tags: ["room", "chair", "hostel"],
    imageStyle: "art-chair",
    imageUrl:
      "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=900&q=80",
    views: 76,
  },
  {
    id: "htu-hoodie",
    title: "Minimal HTU Hoodie",
    price: 140,
    category: "Clothing",
    location: "Auditorium",
    description: "Soft navy hoodie with subtle HTU embroidery. Size medium, worn twice.",
    condition: "Like new",
    postedAt: "4 days ago",
    sellerId: "amara-b",
    seller: sellers[1]!,
    featured: true,
    boosted: false,
    negotiable: true,
    tags: ["hoodie", "fashion", "campus"],
    imageStyle: "art-hoodie",
    imageUrl:
      "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=900&q=80",
    views: 184,
  },
  {
    id: "lecture-notes",
    title: "Data Structures Notes",
    price: 35,
    category: "Notes",
    location: "Computer Lab",
    description: "Neatly organized data structures notes with diagrams, solved questions, and quick revision pages.",
    condition: "New",
    postedAt: "This week",
    sellerId: "sarah-t",
    seller: sellers[2]!,
    featured: false,
    boosted: true,
    negotiable: false,
    tags: ["notes", "computer science", "revision"],
    imageStyle: "art-notes",
    imageUrl:
      "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?auto=format&fit=crop&w=900&q=80",
    views: 221,
  },
  {
    id: "basketball",
    title: "Training Basketball",
    price: 85,
    category: "Sports",
    location: "Sports Complex",
    description: "Durable outdoor basketball, good grip, ready for evening games.",
    condition: "Good",
    postedAt: "This week",
    sellerId: "daniel-k",
    seller: sellers[0]!,
    featured: false,
    boosted: false,
    negotiable: true,
    tags: ["sports", "basketball", "fitness"],
    imageStyle: "art-ball",
    imageUrl:
      "https://images.unsplash.com/photo-1496317899792-9d7dbcd928a1?auto=format&fit=crop&w=900&q=80",
    views: 91,
  },
  {
    id: "drawing-tablet",
    title: "Digital Drawing Tablet",
    price: 420,
    category: "Electronics",
    location: "Design Studio",
    description: "Entry-level drawing tablet for design assignments, illustration, and digital notes.",
    condition: "Good",
    postedAt: "Last week",
    sellerId: "amara-b",
    seller: sellers[1]!,
    featured: true,
    boosted: true,
    negotiable: true,
    tags: ["design", "tablet", "creative"],
    imageStyle: "art-tablet",
    imageUrl:
      "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=80",
    views: 258,
  },
];

export const categories: Category[] = [
  { name: "Electronics", count: 128, icon: Laptop, description: "Phones, laptops, audio gear, tablets" },
  { name: "Textbooks", count: 86, icon: BookOpen, description: "Course books and exam prep material" },
  { name: "Clothing", count: 64, icon: Shirt, description: "Hoodies, sneakers, uniforms, outfits" },
  { name: "Furniture", count: 42, icon: LampDesk, description: "Hostel room desks, chairs, lamps" },
  { name: "Notes", count: 91, icon: FileText, description: "Lecture notes and revision packs" },
  { name: "Sports", count: 35, icon: Dumbbell, description: "Training gear and campus sports items" },
  { name: "Stationery", count: 73, icon: PenTool, description: "Pens, boards, calculators, kits" },
  { name: "Services", count: 58, icon: Scissors, description: "Tutoring, hair styling, repairs, design, errands" },
  { name: "Other", count: 50, icon: Package, description: "Everything else students need" },
];

export const orders: Order[] = [
  { id: "ord-101", product: products[0]!, status: "Awaiting pickup", meetupLocation: "HTU Main Gate", counterpart: "Daniel K.", role: "buyer", updatedAt: "10:40 AM" },
  { id: "ord-102", product: products[4]!, status: "In progress", meetupLocation: "Auditorium", counterpart: "Amara B.", role: "buyer", updatedAt: "Yesterday" },
  { id: "ord-103", product: products[5]!, status: "Completed", meetupLocation: "Computer Lab", counterpart: "Sarah T.", role: "seller", updatedAt: "Fri" },
  { id: "ord-104", product: products[3]!, status: "Cancelled", meetupLocation: "Hostel B", counterpart: "Amara B.", role: "buyer", updatedAt: "Last week" },
];

export const conversations: Conversation[] = [
  {
    id: "daniel",
    user: "Daniel K.",
    avatar: "DK",
    productTitle: "MacBook Air M1 256GB",
    unread: 2,
    timestamp: "11:08 AM",
    online: true,
    messages: [
      { id: "m1", sender: "them", body: "The MacBook is still available. I can meet at the main gate after lectures.", time: "10:52 AM" },
      { id: "m2", sender: "me", body: "Great. Can I check the battery cycle count before payment?", time: "10:56 AM" },
      { id: "m3", sender: "them", body: "Sure. I will bring the charger too.", time: "11:08 AM" },
    ],
  },
  {
    id: "amara",
    user: "Amara B.",
    avatar: "AB",
    productTitle: "Minimal HTU Hoodie",
    unread: 0,
    timestamp: "Yesterday",
    online: false,
    messages: [
      { id: "m4", sender: "them", body: "I have medium and large available.", time: "Yesterday" },
      { id: "m5", sender: "me", body: "Medium works. Is the price negotiable?", time: "Yesterday" },
    ],
  },
  {
    id: "sarah",
    user: "Sarah T.",
    avatar: "ST",
    productTitle: "Data Structures Notes",
    unread: 1,
    timestamp: "Mon",
    online: true,
    messages: [
      { id: "m6", sender: "them", body: "The notes include trees, graphs, sorting, and past questions.", time: "Mon" },
      { id: "m7", sender: "me", body: "Perfect, I can pick it up at the computer lab.", time: "Mon" },
    ],
  },
];

export const reviews: Review[] = [
  { id: "r1", author: "Eli A.", rating: 5, body: "Fast meetup, clean product, and honest description." },
  { id: "r2", author: "Nadia P.", rating: 5, body: "Very responsive seller. The item looked exactly like the listing." },
  { id: "r3", author: "Kojo M.", rating: 4, body: "Smooth campus pickup and fair pricing." },
];
